spring:
  datasource:
    url: jdbc:h2:mem:todo
    username: user
    password: user
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

api:
  base-path: /api/v1