spring:
  datasource:
    url: jdbc:h2:mem:todo
    username: user
    password: user
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

#  kafka:
#    template:
#      default-topic: todo
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    bootstrap-servers: localhost:29092

api:
  base-path: /api/v1